# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('sort', models.CharField(max_length=100)),
            ],
        ),
    ]
