# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('operator', models.CharField(max_length=100)),
            ],
        ),
    ]
