# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Patient'),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 11, 19, 11, 17, 46, 881866, tzinfo=utc)),
        ),
    ]
