# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0002_auto_20161119_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 11, 19, 11, 18, 12, 94594, tzinfo=utc)),
        ),
    ]
