# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 00:02
from __future__ import unicode_literals
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_data',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=timezone.now,verbose_name='data published'),
            preserve_default=False,
        ),
    ]
