# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161109_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_information', models.CharField(max_length=50)),
                ('patient_history', models.CharField(max_length=1000)),
            ],
        ),
    ]
