# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_information',
        ),
        migrations.AddField(
            model_name='patient',
            name='p_age',
            field=models.CharField(default='temporary', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_tel_number',
            field=models.IntegerField(default=0),
        ),
    ]
