# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20161118_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_address',
            field=models.CharField(default='浙江', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_id_num',
            field=models.CharField(default='id', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_marriage',
            field=models.CharField(choices=[('已婚', '已婚'), ('未婚', '未婚')], default='已婚', max_length=2),
        ),
    ]
