# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0002_auto_20161119_1917'),
        ('polls', '0006_auto_20161118_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnose',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='diagnose.Diagnose'),
        ),
    ]
